"""
KOHLER Authentic Product Catalog & Specification Database (60 Genuine Products)
Part of the KOHLER AI Bathroom Designer & Planner (Track 1)
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any


@dataclass
class SustainabilitySpec:
    flow_rate_gpm: Optional[float] = None
    flush_gpf: Optional[float] = None
    watersense: bool = True
    annual_water_savings_l: int = 0
    epd_certified: bool = True
    recycled_content_pct: int = 0


@dataclass
class PlumbingCompatibility:
    requires_wet_wall: bool = True
    rough_in_inches: Optional[float] = None
    supply_line: str = '1/2" NPT'
    drain_diameter: str = '1-1/2" P-Trap'
    water_pressure_min_psi: int = 20
    electrical_req: Optional[str] = None


@dataclass
class KohlerFixture:
    id: str
    art: str
    name: str
    category: str
    series: str
    price_inr: int
    price_usd: int
    width_m: float
    depth_m: float
    height_m: float
    styles: List[str]
    sustainability: SustainabilitySpec
    compatibility: PlumbingCompatibility
    description: str
    clearance_front_m: float = 0.533  # NKBA 21" front minimum
    clearance_side_m: float = 0.381   # NKBA 15" centerline minimum


KOHLER_CATALOG: List[KohlerFixture] = [
    KohlerFixture(
        id='veil-smart-toilet',
        art='K-5401IN-0',
        name='Veil™ Smart One-piece Toilet',
        category='toilets',
        series='Veil',
        price_inr=85000,
        price_usd=1150,
        width_m=0.41,
        depth_m=0.71,
        height_m=0.72,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Sculptural smart one-piece toilet with remote control, heated seat, and automatic bidet cleansing.'
    ),
    KohlerFixture(
        id='reach-one-piece-toilet',
        art='K-3983IN-S-0',
        name='Reach™ One-piece Toilet',
        category='toilets',
        series='Reach',
        price_inr=28000,
        price_usd=375,
        width_m=0.38,
        depth_m=0.68,
        height_m=0.73,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='One-piece round-front toilet with clean skirted trapway, dual flush top actuator, and quiet-close seat.'
    ),
    KohlerFixture(
        id='ove-one-piece-toilet',
        art='K-17688IN-SM-0',
        name='Ove™ One-Piece Toilet',
        category='toilets',
        series='Ove',
        price_inr=32000,
        price_usd=420,
        width_m=0.36,
        depth_m=0.71,
        height_m=0.76,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Compact elongated one-piece toilet with Class Five flushing technology and skirted bowl.'
    ),
    KohlerFixture(
        id='trace-integrated-vanity',
        art='K-30375IN-0',
        name='Trace™ Integrated Top and Basin',
        category='vanities',
        series='Trace',
        price_inr=45000,
        price_usd=600,
        width_m=0.7,
        depth_m=0.46,
        height_m=0.85,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='700 mm integrated vitreous china vanity top and basin with moisture-resistant vanity cabinet.'
    ),
    KohlerFixture(
        id='vive-integrated-vanity',
        art='K-28782IN-0',
        name='Vive™ Integrated Top and Basin',
        category='vanities',
        series='Vive',
        price_inr=48000,
        price_usd=640,
        width_m=0.72,
        depth_m=0.46,
        height_m=0.85,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='720 mm contemporary integrated vanity top with seamless washbasin and soft-close storage drawer.'
    ),
    KohlerFixture(
        id='brazn-vessel-sink',
        art='K-21060IN-0',
        name='Brazn™ 58.4 cm Rectangular Vessel Sink',
        category='vanities',
        series='Brazn',
        price_inr=38000,
        price_usd=510,
        width_m=0.58,
        depth_m=0.38,
        height_m=0.14,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Modernist architectural rectangular vessel sink inspired by Bauhaus geometry with razor-thin edges.'
    ),
    KohlerFixture(
        id='forefront-semi-recessed-basin',
        art='K-11479IN-VC1-0',
        name='Forefront™ Square Semi-Recessed Basin',
        category='vanities',
        series='Forefront',
        price_inr=22000,
        price_usd=295,
        width_m=0.41,
        depth_m=0.41,
        height_m=0.18,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Clean geometric semi-recessed basin projecting past the counter edge for effortless ergonomic wash reach.'
    ),
    KohlerFixture(
        id='new-trilogy-pivot-door',
        art='K-704699IN-SHP',
        name='New Trilogy™ 2000–2161 mm H Pivot Door',
        category='showers',
        series='New Trilogy',
        price_inr=82000,
        price_usd=1100,
        width_m=0.9,
        depth_m=0.9,
        height_m=2.05,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Architectural 2.05m tall pivot shower door with 8 mm CleanCoat tempered glass and solid brass pivot hinges.'
    ),
    KohlerFixture(
        id='statement-round-showerhead',
        art='K-26299IN-CP',
        name='Statement™ Round Multifunction Showerhead',
        category='showers',
        series='Statement',
        price_inr=35000,
        price_usd=470,
        width_m=0.3,
        depth_m=0.45,
        height_m=1.1,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Statement round multifunction showerhead delivering Full Coverage with Katalyst air-induction technology.'
    ),
    KohlerFixture(
        id='evok-2-bathtub',
        art='K-20935IN-0',
        name='Evok 2.0™ 1600 mm Acrylic Bathtub',
        category='bathtubs',
        series='Evok 2.0',
        price_inr=125000,
        price_usd=1680,
        width_m=1.6,
        depth_m=0.75,
        height_m=0.6,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Seamless rectangular freestanding acrylic bathtub with ergonomic lumbar backrest and center toe-tap drain.'
    ),
    KohlerFixture(
        id='ming-lighted-mirror',
        art='K-77115IN-NA',
        name='Ming™ 80 cm Lighted Mirror',
        category='mirrors',
        series='Ming',
        price_inr=42000,
        price_usd=560,
        width_m=0.8,
        depth_m=0.05,
        height_m=0.8,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='80 cm circular lighted smart mirror with proximity sensor, perimeter frosted LED halo, and defogger.'
    ),
    KohlerFixture(
        id='reve-lighted-mirror',
        art='K-23268IN-NA',
        name='Reve™ 1000 mm Lighted Mirror',
        category='mirrors',
        series='Reve',
        price_inr=56000,
        price_usd=750,
        width_m=1.0,
        depth_m=0.05,
        height_m=0.65,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='1000 mm rectangular luxury lighted mirror with integrated LED lighting border and touch dimmer control.'
    ),
    KohlerFixture(
        id='purist-single-control-faucet',
        art='K-14402IN-4A-CP',
        name='Purist™ Single Control Lavatory Faucet',
        category='faucets',
        series='Purist',
        price_inr=22000,
        price_usd=295,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.22,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Iconic architectural single-lever lavatory faucet with straight ergonomic spout and ceramic disc cartridge.'
    ),
    KohlerFixture(
        id='parallel-pillar-tap',
        art='K-23482IN-4-BV',
        name='Parallel™ Pillar Tap',
        category='faucets',
        series='Parallel',
        price_inr=16000,
        price_usd=215,
        width_m=0.13,
        depth_m=0.15,
        height_m=0.18,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Precision-machined pillar tap with distinctive flat spout and knurled quarter-turn handle in Vibrant Brushed Bronze.'
    ),
    KohlerFixture(
        id='artifacts-widespread-faucet',
        art='K-72760T-CP',
        name='Artifacts™ Widespread Sink Faucets',
        category='faucets',
        series='Artifacts',
        price_inr=34000,
        price_usd=450,
        width_m=0.3,
        depth_m=0.2,
        height_m=0.19,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Edwardian swan neck spout with dual porcelain-capped cross handles in polished chrome.'
    ),
    KohlerFixture(
        id='composed-tall-faucet',
        art='K-73159IN-7-CP',
        name='Composed™ Tall Single-handle Faucet',
        category='faucets',
        series='Composed',
        price_inr=22000,
        price_usd=295,
        width_m=0.15,
        depth_m=0.2,
        height_m=0.31,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Tower vessel column with side joystick lever and flat horizontal spout, 1.2 GPM WaterSense.'
    ),
    KohlerFixture(
        id='eap-eap-ne-piece-ound-front-mart-oil-k28529in',
        art='K-28529IN-0',
        name='Leap™ One-piece Round-front Smart Toilet',
        category='toilets',
        series='Leap',
        price_inr=78000,
        price_usd=1040,
        width_m=0.4,
        depth_m=0.67,
        height_m=0.7,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Intelligent one-piece compact round-front smart toilet with personalized bidet wand, warm-air dryer, and wireless remote.'
    ),
    KohlerFixture(
        id='nnate-nnate-ne-piece-longated-mart-o-k29777in',
        art='K-29777IN-0',
        name='Innate™ One-piece Elongated Smart Toilet',
        category='toilets',
        series='Innate',
        price_inr=92000,
        price_usd=1230,
        width_m=0.41,
        depth_m=0.73,
        height_m=0.71,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Architectural elongated smart toilet featuring dual-flush power, stainless steel cleansing wand, and ambient LED bowl nightlight.'
    ),
    KohlerFixture(
        id='ive-ne-piece-ound-front-oilet-k33123in',
        art='K-33123IN-0',
        name='KOHLER VIVE® One-piece Round-front Toilet',
        category='toilets',
        series='Vive',
        price_inr=31000,
        price_usd=415,
        width_m=0.38,
        depth_m=0.68,
        height_m=0.74,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Modern round-front one-piece toilet with smooth contoured bowl and high-efficiency 3.8/4.8L dual flush.'
    ),
    KohlerFixture(
        id='ive-ne-piece-ound-front-oilet-k33124in',
        art='K-33124IN-S-0',
        name='KOHLER VIVE® One-piece Round-front Toilet',
        category='toilets',
        series='Vive',
        price_inr=33500,
        price_usd=445,
        width_m=0.38,
        depth_m=0.68,
        height_m=0.74,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=1.28, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='One-piece round-front toilet with skirted trapway design for effortless wiping and quiet-close slim seat.'
    ),
    KohlerFixture(
        id='eil-eil-16-ound-essel-athroom-ink-k207030',
        art='K-20703-0',
        name='Veil™ 16" Round Vessel Bathroom Sink',
        category='vanities',
        series='Veil',
        price_inr=32000,
        price_usd=425,
        width_m=0.41,
        depth_m=0.41,
        height_m=0.13,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Sensuous 16-inch circular vessel sink with flowing Supramic ceramic curves and ultra-thin 4mm rim profile.'
    ),
    KohlerFixture(
        id='eil-eil-38-1-2-val-essel-athroom-ink-k207050',
        art='K-20705-0',
        name='Veil™ 38-1/2" Oval Vessel Bathroom Sink',
        category='vanities',
        series='Veil',
        price_inr=58000,
        price_usd=775,
        width_m=0.98,
        depth_m=0.46,
        height_m=0.14,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Extra-wide 38.5-inch organic oval statement vessel sink creating a striking luxury centerpiece in master suites.'
    ),
    KohlerFixture(
        id='eil-eil-12-1-4-edestal-athroom-ink-k207020',
        art='K-20702-0',
        name='Veil™ 12-1/4" Pedestal Bathroom Sink',
        category='vanities',
        series='Veil',
        price_inr=68000,
        price_usd=910,
        width_m=0.46,
        depth_m=0.51,
        height_m=0.86,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Sculptural monolithic pedestal sink tapering organically from floor to basin with concealed floor waste coupling.'
    ),
    KohlerFixture(
        id='eil-eil-21-val-essel-athroom-ink-k207040',
        art='K-20704-0',
        name='Veil™ 21" Oval Vessel Bathroom Sink',
        category='vanities',
        series='Veil',
        price_inr=36000,
        price_usd=480,
        width_m=0.53,
        depth_m=0.38,
        height_m=0.13,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='21-inch balanced oval vessel bathroom sink with flowing organic contours and stain-resistant glaze.'
    ),
    KohlerFixture(
        id='adena-adena-emi-ecessed-athroom-ink-k72907k1',
        art='K-72907K-1-0',
        name='Ladena™ Semi-Recessed Bathroom Sink',
        category='vanities',
        series='Ladena',
        price_inr=24000,
        price_usd=320,
        width_m=0.53,
        depth_m=0.46,
        height_m=0.17,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Gracefully contoured rectangular semi-recessed sink with deep basin geometry and overflow channel.'
    ),
    KohlerFixture(
        id='orefront-orefront-emi-ecessed-athroo-k98930x1',
        art='K-98930X-1-0',
        name='Forefront™ Semi-Recessed Bathroom Sink',
        category='vanities',
        series='Forefront',
        price_inr=26000,
        price_usd=345,
        width_m=0.56,
        depth_m=0.46,
        height_m=0.17,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Architectural semi-recessed basin featuring crisp parallel lines, wide rear deck for faucet, and rounded basin interior.'
    ),
    KohlerFixture(
        id='eil-eil-59-9-cm-val-essel-athroom-in-k77171in',
        art='K-77171IN-0',
        name='Veil™ 59.9 cm Oval Vessel Bathroom Sink',
        category='vanities',
        series='Veil',
        price_inr=39000,
        price_usd=520,
        width_m=0.6,
        depth_m=0.4,
        height_m=0.14,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='60 cm asymmetric organic vessel sink crafted in high-performance Supramic material with concealed overflow.'
    ),
    KohlerFixture(
        id='omposed-omposed-all-mount-avatory-au-k73061t7',
        art='K-73061T-7-BV',
        name='Composed™ Wall-mount Lavatory Faucet',
        category='faucets',
        series='Composed',
        price_inr=31000,
        price_usd=415,
        width_m=0.23,
        depth_m=0.2,
        height_m=0.1,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Wall-mount single-control lavatory faucet with 200 mm reach spout in Vibrant Brushed Bronze.'
    ),
    KohlerFixture(
        id='omposed-omposed-all-mount-athroom-in-k73061in',
        art='K-73061IN-4ND-CP',
        name='Composed™ Wall-mount Bathroom Sink Faucet',
        category='faucets',
        series='Composed',
        price_inr=28000,
        price_usd=375,
        width_m=0.23,
        depth_m=0.2,
        height_m=0.1,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Clean geometric wall-mounted faucet in Polished Chrome with minimal wall plate and aerated laminar stream.'
    ),
    KohlerFixture(
        id='omposed-omposed-ingle-handle-athroom-k73050tb',
        art='K-73050T-B7-BL',
        name='Composed™ Single-handle Bathroom Sink Faucet',
        category='faucets',
        series='Composed',
        price_inr=26000,
        price_usd=345,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.21,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Matte Black single-handle deck-mount faucet with pure geometric proportions and top lever control.'
    ),
    KohlerFixture(
        id='omposed-omposed-ingle-handle-aucet-w-k73158t4',
        art='K-73158T-4-RGD',
        name='Composed™ Single-handle Faucet with Joystick Handle',
        category='faucets',
        series='Composed',
        price_inr=29000,
        price_usd=390,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.22,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Rose Gold luxury single-control faucet featuring a precision side-joystick actuator for feather-touch regulation.'
    ),
    KohlerFixture(
        id='omposed-omposed-ingle-handle-aucet-k7305072',
        art='K-73050-7-2MB',
        name='Composed™ Single-handle Faucet',
        category='faucets',
        series='Composed',
        price_inr=27500,
        price_usd=365,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.21,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Vibrant Brushed Moderne Brass single-control lavatory faucet with solid brass body and ceramic disc valve.'
    ),
    KohlerFixture(
        id='omposed-omposed-ingle-handle-aucet-4-k73050t7',
        art='K-73050T-7GCH-TT',
        name='Composed™ Single-handle Faucet, 4.5 LPM',
        category='faucets',
        series='Composed',
        price_inr=28500,
        price_usd=380,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.21,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Titanium finish ultra-efficient 4.5 LPM water-saving single-handle faucet engineered for LEED-certified green suites.'
    ),
    KohlerFixture(
        id='omposed-omposed-2-handle-all-mounted-k73067t9',
        art='K-73067T-9ACH-BV',
        name='Composed™ 2-handle Wall-mounted Lavatory Faucet',
        category='faucets',
        series='Composed',
        price_inr=36000,
        price_usd=480,
        width_m=0.25,
        depth_m=0.23,
        height_m=0.11,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Dual-handle three-hole wall-mount lavatory faucet with independent hot and cold cross valves in Brushed Bronze.'
    ),
    KohlerFixture(
        id='omposed-omposed-all-ingle-handle-auc-k73159tb',
        art='K-73159T-B7-AF',
        name='Composed™ Tall Single-handle Faucet',
        category='faucets',
        series='Composed',
        price_inr=27000,
        price_usd=360,
        width_m=0.15,
        depth_m=0.2,
        height_m=0.31,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Vibrant French Gold tall tower faucet designed to provide generous clearance above elevated vessel basins.'
    ),
    KohlerFixture(
        id='leo-leo-ingle-handle-athroom-ink-auc-k72275in',
        art='K-72275IN-4ND-RGD',
        name='Aleo™ Single-handle Bathroom Sink Faucet',
        category='faucets',
        series='Aleo',
        price_inr=18500,
        price_usd=245,
        width_m=0.15,
        depth_m=0.17,
        height_m=0.19,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Rose Gold sleek single-handle faucet with forward-angled spout and integrated coin-slot aerator.'
    ),
    KohlerFixture(
        id='leo-leo-all-ingle-handle-athroom-ink-k72298in',
        art='K-72298IN-4ND-RGD',
        name='Aleo™ Tall Single-handle Bathroom Sink Faucet',
        category='faucets',
        series='Aleo',
        price_inr=23000,
        price_usd=310,
        width_m=0.15,
        depth_m=0.2,
        height_m=0.3,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Extended tower vessel faucet in Rose Gold with sculpted ergonomic handle and smooth water delivery.'
    ),
    KohlerFixture(
        id='one-one-ingle-ontrol-av-aucet-with-r-k22534in',
        art='K-22534IN-4-CP',
        name='Hone™ Single Control Lav Faucet with Drain',
        category='faucets',
        series='Hone',
        price_inr=15500,
        price_usd=210,
        width_m=0.15,
        depth_m=0.18,
        height_m=0.18,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Polished Chrome cylindrical single-control faucet with pop-up clicker drain and durable brass waterway.'
    ),
    KohlerFixture(
        id='odern-ife-odern-ife-dge-all-ingle-ha-k25758in',
        art='K-25758IN-4ND-CP',
        name='ModernLife Edge™ Tall Single-handle Faucet',
        category='faucets',
        series='ModernLife',
        price_inr=24500,
        price_usd=325,
        width_m=0.15,
        depth_m=0.2,
        height_m=0.32,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Ultra-slim architectural tall vessel faucet with razor-thin lever and crisp planar surfaces.'
    ),
    KohlerFixture(
        id='omplementary-omplementary-ingle-hand-k5679inc',
        art='K-5679IN-CP',
        name='Complementary™ Single-handle Wall-mount Faucet Valve',
        category='faucets',
        series='Complementary',
        price_inr=12000,
        price_usd=160,
        width_m=0.15,
        depth_m=0.08,
        height_m=0.15,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.2, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Solid brass concealed wall-mount rough-in valve with polished chrome decorative faceplate.'
    ),
    KohlerFixture(
        id='late-late-200-cm-liding-hower-oor-k39061in',
        art='K-39061IN-SHP',
        name='Elate™ 200 cm H Sliding Shower Door',
        category='showers',
        series='Elate',
        price_inr=74000,
        price_usd=990,
        width_m=1.2,
        depth_m=0.9,
        height_m=2.0,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='120 cm wide 2-meter tall sliding glass shower door with oversized top rollers and Bright Polished Silver header.'
    ),
    KohlerFixture(
        id='ew-rilogy-ew-rilogy-206-1-cm-ivot-ho-k704796i',
        art='K-704796IN-2BL',
        name='New Trilogy™ 206.1 cm H Pivot Shower Door',
        category='showers',
        series='New Trilogy',
        price_inr=86000,
        price_usd=1150,
        width_m=0.9,
        depth_m=0.9,
        height_m=2.06,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Matte Black framed pivot shower door standing 2.06m tall with heavy-duty 8mm tempered glass.'
    ),
    KohlerFixture(
        id='ew-rilogy-ew-rilogy-2000-mm-ivot-how-k704702i',
        art='K-704702IN-SHP',
        name='New Trilogy™ 2000 mm H Pivot Shower Door',
        category='showers',
        series='New Trilogy',
        price_inr=79000,
        price_usd=1050,
        width_m=0.9,
        depth_m=0.9,
        height_m=2.0,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='High-gloss silver pivot shower door with continuous magnetic catch and outward-opening clearance.'
    ),
    KohlerFixture(
        id='ontra-ontra-200-cm-liding-hower-oor-k705116i',
        art='K-705116IN-SHP',
        name='Contra™ 200 cm H Sliding Shower Door',
        category='showers',
        series='Contra',
        price_inr=76000,
        price_usd=1015,
        width_m=1.2,
        depth_m=0.9,
        height_m=2.0,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Frameless sliding shower enclosure with exposed stainless steel dual roller wheels and soft-cushion stops.'
    ),
    KohlerFixture(
        id='ew-rilogy-ew-rilogy-200-216-1-cm-ivo-k704699i',
        art='K-704699IN-SHP',
        name='New Trilogy™ 200–216.1 cm H Pivot Shower Door',
        category='showers',
        series='New Trilogy',
        price_inr=84000,
        price_usd=1120,
        width_m=1.0,
        depth_m=0.9,
        height_m=2.05,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='100 cm wide adjustable pivot shower door with full-length clear water seals and ergonomic towel bar handle.'
    ),
    KohlerFixture(
        id='late-late-200-cm-liding-hower-oor-k39060in',
        art='K-39060IN-SHP',
        name='Elate™ 200 cm H Sliding Shower Door',
        category='showers',
        series='Elate',
        price_inr=71000,
        price_usd=950,
        width_m=1.05,
        depth_m=0.9,
        height_m=2.0,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='105 cm compact sliding shower door with smooth bypass action and low threshold for easy walk-in entry.'
    ),
    KohlerFixture(
        id='ontra-ontra-200-210-cm-liding-hower-k705115i',
        art='K-705115IN-SHP',
        name='Contra™ 200–210 cm H Sliding Shower Door',
        category='showers',
        series='Contra',
        price_inr=77000,
        price_usd=1030,
        width_m=1.15,
        depth_m=0.9,
        height_m=2.05,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Adjustable height 200-210cm sliding shower door with CleanCoat hydrophobic surface protection.'
    ),
    KohlerFixture(
        id='ew-evity-ew-evity-200-cm-liding-howe-k709076i',
        art='K-709076IN-CP',
        name='New Levity™ 200 cm H Sliding Shower Door',
        category='showers',
        series='New Levity',
        price_inr=79000,
        price_usd=1055,
        width_m=1.2,
        depth_m=0.9,
        height_m=2.0,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='Dual-sliding bypass glass shower door system with cushioned center guide and minimalist top track.'
    ),
    KohlerFixture(
        id='ingulier-ingulier-200-212-1-cm-ivot-k708066i',
        art='K-708066IN-CP',
        name='Singulier™ 200–212.1 cm H Pivot Shower Door',
        category='showers',
        series='Singulier',
        price_inr=81000,
        price_usd=1080,
        width_m=0.9,
        depth_m=0.9,
        height_m=2.05,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=1.75, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='French architectural pivot shower door with integrated rise-and-fall hinge mechanism preventing seal drag.'
    ),
    KohlerFixture(
        id='rcher-rcher-51-78-7-cm-irrored-abine-k3073inn',
        art='K-3073IN-NA',
        name='Archer™ 51 × 78.7 cm Mirrored Cabinet',
        category='mirrors',
        series='Archer',
        price_inr=29000,
        price_usd=390,
        width_m=0.51,
        depth_m=0.13,
        height_m=0.79,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='51x79 cm reversible mirrored cabinet with beveled glass door, 3 adjustable glass shelves, and rust-free aluminum body.'
    ),
    KohlerFixture(
        id='orefront-orefront-90-cm-all-hung-ani-k31601in',
        art='K-31601IN-E64',
        name='Forefront™ 90 cm Wall-hung Vanity Cabinet',
        category='vanities',
        series='Forefront',
        price_inr=52000,
        price_usd=695,
        width_m=0.9,
        depth_m=0.46,
        height_m=0.55,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='90 cm wall-hung floating vanity cabinet in Nordic Oak finish with full-extension soft-close dual drawers.'
    ),
    KohlerFixture(
        id='oreward-oreward-75-cm-all-hung-anity-k28741in',
        art='K-28741IN-RWP',
        name='Foreward™ 75 cm Wall-hung Vanity Cabinet',
        category='vanities',
        series='Foreward',
        price_inr=44000,
        price_usd=590,
        width_m=0.75,
        depth_m=0.46,
        height_m=0.55,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='75 cm contemporary timber wall-hung vanity with integrated finger-pull drawer fronts and plumbing cutout.'
    ),
    KohlerFixture(
        id='orefront-orefront-60-cm-all-hung-ani-k31602in',
        art='K-31602IN-E64',
        name='Forefront™ 60 cm Wall-hung Vanity Cabinet',
        category='vanities',
        series='Forefront',
        price_inr=38000,
        price_usd=510,
        width_m=0.6,
        depth_m=0.46,
        height_m=0.55,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='60 cm compact powder room floating vanity cabinet with deep bottom storage and moisture-resistant lacquer.'
    ),
    KohlerFixture(
        id='odern-ife-odern-ife-51-101-8-cm-apsu-k37876in',
        art='K-37876IN-NA',
        name='ModernLife™ 51 × 101.8 cm Capsule Lighted Mirror',
        category='mirrors',
        series='ModernLife',
        price_inr=48000,
        price_usd=640,
        width_m=0.51,
        depth_m=0.05,
        height_m=1.02,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='51x102 cm pill-capsule vertical lighted mirror with diffuse perimeter glow, touch sensor, and anti-fog heating pad.'
    ),
    KohlerFixture(
        id='orefront-ite-orefront-ite-72-65-cm-i-k29155in',
        art='K-29155IN-NA',
        name='Forefront™ Lite 72 × 65 cm Lighted Mirror',
        category='mirrors',
        series='Forefront Lite',
        price_inr=36000,
        price_usd=480,
        width_m=0.72,
        depth_m=0.05,
        height_m=0.65,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='72x65 cm rectangular backlit LED mirror providing uniform indirect task lighting for grooming.'
    ),
    KohlerFixture(
        id='orefront-ite-orefront-ite-90-65-cm-i-k29156in',
        art='K-29156IN-NA',
        name='Forefront™ Lite 90 × 65 cm Lighted Mirror',
        category='mirrors',
        series='Forefront Lite',
        price_inr=42000,
        price_usd=560,
        width_m=0.9,
        depth_m=0.05,
        height_m=0.65,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='90x65 cm wide lighted mirror ideal for double vanities with 3000K/4000K dual-color circadian toggle.'
    ),
    KohlerFixture(
        id='ssential-ssential-60-120-cm-apsule-r-k38367in',
        art='K-38367IN-BLL',
        name='Essential 60 × 120 cm Capsule Framed Mirror',
        category='mirrors',
        series='Essential',
        price_inr=34000,
        price_usd=450,
        width_m=0.6,
        depth_m=0.04,
        height_m=1.2,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='60x120 cm elongated capsule mirror enclosed in a clean Matte Black anodized aluminum metal rim.'
    ),
    KohlerFixture(
        id='ssential-ssential-61-6-92-1-cm-rched-k30637in',
        art='K-30637IN-BLL',
        name='Essential 61.6 × 92.1 cm Arched Framed Mirror',
        category='mirrors',
        series='Essential',
        price_inr=32000,
        price_usd=425,
        width_m=0.62,
        depth_m=0.04,
        height_m=0.92,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='62x92 cm classic Roman arch framed mirror with slender black profile and distortion-free copper-free backing.'
    ),
    KohlerFixture(
        id='mbark-mbark-remium-rched-irrored-abi-k56151in',
        art='K-56151IN-NA',
        name='Embark™ Premium XL Arched Mirrored Cabinet',
        category='mirrors',
        series='Embark',
        price_inr=54000,
        price_usd=720,
        width_m=0.6,
        depth_m=0.14,
        height_m=0.96,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=False),
        description='Architectural arched mirrored medicine cabinet featuring internal LED lighting, magnetic organizer bar, and double-sided mirror door.'
    ),
    KohlerFixture(
        id='ve-ve-170-75-cm-rop-in-hirlpool-ath-k1709ink',
        art='K-1709IN-K-0',
        name='Ove™ 170 × 75 cm Drop-in Whirlpool Bath',
        category='bathtubs',
        series='Ove',
        price_inr=165000,
        price_usd=2200,
        width_m=1.7,
        depth_m=0.75,
        height_m=0.58,
        styles=['minimalist', 'zen', 'modern', 'luxury', 'classic'],
        sustainability=SustainabilitySpec(flow_rate_gpm=None, flush_gpf=None, watersense=True, annual_water_savings_l=12000),
        compatibility=PlumbingCompatibility(requires_wet_wall=True),
        description='170 cm drop-in hydrotherapy whirlpool bathtub with 6 adjustable hydromassage body jets and quiet-flow pump.'
    )
]

def get_fixture_by_id(fixture_id: str) -> Optional[KohlerFixture]:
    for f in KOHLER_CATALOG:
        if f.id == fixture_id:
            return f
    return None

def get_fixtures_by_category(category: str) -> List[KohlerFixture]:
    return [f for f in KOHLER_CATALOG if f.category == category]

get_catalog_by_id = get_fixture_by_id
get_catalog_by_category = get_fixtures_by_category

